apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    app.kubernetes.io/component: security
data:
  vault.hcl: |
    # Vault configuration for Consciousness Engine
    
    # Storage backend - AWS DynamoDB for HA
    storage "dynamodb" {
      table      = "consciousness-engine-vault-storage"
      region     = "us-west-2"
      ha_enabled = "true"
    }
    
    # Listener configuration
    listener "tcp" {
      address       = "0.0.0.0:8200"
      tls_cert_file = "/vault/tls/tls.crt"
      tls_key_file  = "/vault/tls/tls.key"
      
      # Security headers
      tls_min_version = "tls12"
      tls_cipher_suites = "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
      
      # Telemetry
      telemetry {
        unauthenticated_metrics_access = false
      }
    }
    
    # API address
    api_addr = "https://vault.consciousness-engine.com:8200"
    cluster_addr = "https://vault.consciousness-engine.com:8201"
    
    # UI configuration
    ui = true
    
    # Logging
    log_level = "INFO"
    log_format = "json"
    
    # Disable mlock for Kubernetes
    disable_mlock = true
    
    # Enable service registration
    service_registration "kubernetes" {
      namespace      = "vault"
      pod_name       = "vault"
    }
    
    # Seal configuration - AWS KMS Auto Unseal
    seal "awskms" {
      region     = "us-west-2"
      kms_key_id = "alias/consciousness-engine-vault-unseal"
    }
    
    # Telemetry
    telemetry {
      prometheus_retention_time = "30s"
      disable_hostname = true
      
      # Metrics prefixes for consciousness-specific monitoring
      prefix_filter = [
        "vault.audit",
        "vault.core",
        "vault.runtime",
        "vault.expire",
        "vault.policy",
        "vault.token",
        "vault.secret",
        "vault.auth",
        "vault.route"
      ]
    }
    
    # Plugin directory
    plugin_directory = "/vault/plugins"
    
    # Default lease TTL
    default_lease_ttl = "768h"
    max_lease_ttl = "8760h"
    
    # Cluster configuration
    cluster_name = "consciousness-engine-vault"
    
    # Raw storage endpoint (disabled for security)
    raw_storage_endpoint = false
    
    # Introspection endpoint (disabled for security)
    introspection_endpoint = false
    
    # Disable clustering for single instance (enable for HA)
    disable_clustering = false
    
    # Cache size
    cache_size = "32000"