apiVersion: v1
kind: Secret
metadata:
  name: consciousness-secrets
  namespace: consciousness-system
  labels:
    app.kubernetes.io/name: consciousness-engine
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database credentials
  POSTGRES_PASSWORD: "consciousness_secure_k8s_2024"
  DATABASE_URL: "postgresql://consciousness:consciousness_secure_k8s_2024@postgres:5432/consciousness"
  
  # Redis credentials
  REDIS_PASSWORD: "redis_secure_k8s_2024"
  REDIS_URL: "redis://:redis_secure_k8s_2024@redis:6379"
  
  # JWT secret for authentication
  JWT_SECRET_KEY: "consciousness_jwt_super_secret_key_2024_k8s_deployment"
  
  # API keys for external services
  OPENAI_API_KEY: "your-openai-api-key-here"
  ANTHROPIC_API_KEY: "your-anthropic-api-key-here"
  
  # Monitoring credentials
  GRAFANA_PASSWORD: "grafana_admin_secure_2024"
  
  # Encryption keys
  ENCRYPTION_KEY: "consciousness_encryption_key_32_chars"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: consciousness-system
  labels:
    app.kubernetes.io/name: consciousness-engine
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  # Generate with: kubectl create secret tls tls-secret --cert=path/to/tls.crt --key=path/to/tls.key
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...